version: "3"

services:
  jenkins:
    build: 
      context: .
#    image: jenkins:2.60.2
    container_name: jenkins-2.89.3
    expose:
      - 8080
      - 50000
    environment:
      - "VIRTUAL_HOST=jenkins.grassy.se"
      - "VIRTUAL_PORT=8080"
      - "HTTPS_METHOD=noredirect"
#      - "JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="
    volumes:
      - jenkins-data:/var/jenkins_home
#      - "/opt/apps/jenkins_old/data:/var/jenkins_home"
#      - "/var/run/docker.sock:/var/run/docker.sock" 
    restart: always
    network_mode: "bridge"
    
volumes:
  jenkins-data:
