jenkins:
  image: jenkins
  container_name: jenkins
  expose:
    - 8080
    - 50000
  environment:
    - "VIRTUAL_HOST=jenkins.grassy.com"
    - "VIRTUAL_PORT=8080"
    - "HTTPS_METHOD=noredirect" # Github webook needs http 
  volumes:
    - "./data:/var/jenkins_home"
