version: "3"

services:
  jenkins:
    build: 
      context: .
    container_name: jenkins-{version}
    expose:
      - 8080
      - 50000
    environment:
      - "VIRTUAL_HOST={virtual-host}"
      - "VIRTUAL_PORT=8080"
      - "HTTPS_METHOD=noredirect" # Github webook needs http
#      - "JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="
    volumes:
      - home:/var/jenkins_home
      - "/var/run/docker.sock:/var/run/docker.sock" 
    restart: always
    network_mode: "bridge"
    
volumes:
  home:
